# 🔐 Password Strength Prediction

### Machine Learning + NLP Project

This project analyzes password patterns and builds a machine learning model to classify passwords into three strength levels:

- **0 → Weak**
- **1 → Medium**
- **2 → Strong**

**Workflow:**  
Data Collection → Data Cleaning → EDA → Feature Engineering → NLP/TF-IDF → Model Training → Password Strength Prediction

# Getting Startred....

In [1]:
#import all the basic libraries ...
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# Read the data from sql database...

In [3]:
import sqlite3

In [4]:
## u have your data into 'password_Data.sqlite' which has table  'Users' 
## now u can read data from this db file 'password_Data.sqlite' using sqlite3 & pandas

In [8]:
#first off all we have to create sql connection to the sql database
con = sqlite3.connect(r"password_data.sqlite")

In [9]:
'''check online its table name on https://sqliteonline.com/'''
data = pd.read_sql_query("SELECT * FROM  Users",con)

In [10]:
data.shape

(100000, 3)

In [11]:
data.head()

   index                 password  strength
0      0                zxe870819         1
1      1             xw46454nr23l         1
2      2                soporte13         1
3      3  accounts6000webhost.com         2
4      4                 c443balg         1

# 2.. Doing basic data cleaning !

In [12]:
data.columns

Index(['index', 'password', 'strength'], dtype='str')

### Removing ir-relevant features !

In [13]:
data.drop('index',axis = 1,inplace = True)

In [14]:
data.head()

                  password  strength
0                zxe870819         1
1             xw46454nr23l         1
2                soporte13         1
3  accounts6000webhost.com         2
4                 c443balg         1

### Check duplicate rows

In [17]:
data.duplicated().sum()

np.int64(0)